#!/usr/bin/expect -f
spawn $env(SUBJECTS_SRC_DIR)/vim-5.8 -u $env(HOME)/.vimrc $env(TESTS_SRC)/copy1
expect "copy1"
sleep 1
send ":se lines=24\r"
send ":se columns=80\r"
send ":redir >> move_261.1.1.out\r"
send "j"
send "i"
send " "
send "\033"
send "k"
send "0"
send "2H"
send "\007"
#expect "Modified"
send ":redir END\r"

send ":wq\r"
expect
exit -onexit {
interact
}
