#!/usr/bin/expect -f
spawn $env(SUBJECTS_SRC_DIR)/vim-5.8 -u $env(HOME)/.vimrc $env(TESTS_SRC)/copy1
expect "copy1"
sleep 1
send ":se lines=24\r"
send ":se columns=80\r"
send ":redir >> move_263.1.1.out\r"
send "i		\033"
send "j"
send "\007"
send "H"
send ":redir END\r"

send ":wq\r"
expect
exit -onexit {
interact
}
