#!/usr/bin/expect -f
spawn $env(SUBJECTS_SRC_DIR)/vim-5.8 -u $env(HOME)/.vimrc $env(TESTS_SRC)/copy1
expect "copy1*1364C"
sleep 1
send ":se lines=24\r"
send ":se columns=80\r"
send ":redir >> move_312.5.1.out\r"
send ":ts f*\r"
send "4\r"
send ":3 tp\r"
send ":redir END\r"
send ":wq\r"
expect
exit -onexit {
interact
}
