#!/usr/bin/expect -f
set force_conservative 1;
if {$force_conservative} {
        set send_slow {1 .1}
        proc send {ignore arg} {
                sleep .1
                exp_send -s -- $arg
        }
}
spawn $env(SUBJECTS_SRC_DIR)/vim-5.8 -u $env(HOME)/.vimrc $env(TESTS_SRC)/copy1
expect "copy1"
sleep 1
send -- ":se lines=24\r"
send -- ":se columns=80\r"
send -- ":redir >> edit_242.1.1.out\r"
send -- "qb"
expect "recording"
send -- "2j"
send -- "q"
send -- ":reg b\r"
expect "continue"
send -- ":1\r"
expect "continue"
#expect "RETURN"
#send "\r"
send -- "\007"
send -- "@b"
send -- "\007"
send -- ":redir END\r"
send -- ":wq\r"
expect
exit -onexit {
interact
}
