#!/usr/bin/expect -f
set force_conservative 1;
if {$force_conservative} {
        set send_slow {1 .1}
        proc send {ignore arg} {
                sleep .1
                exp_send -s -- $arg
        }
}
spawn $env(SUBJECTS_SRC_DIR)/vim-5.8 -u $env(HOME)/.vimrc $env(TESTS_SRC)/copy1
expect "copy1"
sleep 1
send -- ":se lines=24\r"
send -- ":se columns=80\r"
send -- ":dig a^ 290 b^ 299\r"
send -- "i"
send -- "\013"
send -- "a^\r"
send -- "\013"
send -- "b^\r"
send -- "\033"

send -- ":wq\r"
expect
exit -onexit {
interact
}
