#!/usr/bin/expect -f
spawn $env(SUBJECTS_SRC_DIR)/vim-5.8 -u $env(HOME)/.vimrc $env(TESTS_SRC)/copy1
expect "copy1"
sleep 1
send ":se lines=24\r"
send ":se columns=80\r"
send ":redir >> mapping_17.1.1.out\r"
send ":imap b l\r"
send ":imap b\r"
send ":iunmap b\r"
send ":imap b\r"
send ":redir END\r"

send ":wq\r"
expect
exit -onexit {
interact
}
