#!/usr/bin/expect -f
spawn $env(SUBJECTS_SRC_DIR)/vim-5.8 -u $env(HOME)/.vimrc $env(TESTS_SRC)/copy1
expect "copy1"
sleep 1
send ":se lines=24\r"
send ":se columns=80\r"
send ":redir >> mapping_47.1.1.out\r"
send ":ab a abbreviate\r"
send ":ab abb abbreviation\r"
send ":ab m mappings\r"
send ":ab\r"
send ":abc\r"
send ":ab\r"
send ":redir END\r"
send ":wq\r"
expect
exit -onexit {
interact
}
