#!/usr/bin/expect -f
spawn $env(SUBJECTS_SRC_DIR)/vim-5.8 -u $env(HOME)/.vimrc $env(TESTS_SRC)/copy1
expect "copy1"
sleep 1
send ":se lines=24\r"
send ":se columns=80\r"
send ":redir >> option_79.1.1.out\r"
send ":set hi=40\r"
send ":set hi?\r"
send ":redir END\r"

send ":wq\r"
expect
exit -onexit {
interact
}
