#!/usr/bin/expect -f
set force_conservative 1;
if {$force_conservative} {
        set send_slow {1 .1}
        proc send {ignore arg} {
                sleep .1
                exp_send -s -- $arg
        }
}
spawn $env(SUBJECTS_SRC_DIR)/vim-5.8 -u $env(HOME)/.vimrc $env(TESTS_SRC)/copy1
expect "copy1"
#expect "wonderful"
#expect "regA"
#expect "main"
#expect "\}"
send -- ":set makeef=/tmp/vim99.err\r"
send -- ":se lines=24\r"
send -- ":se columns=80\r"
send --  ":redir >> other_15.1.4.out\r"
send --  ":make  -C $env(TESTS_SRC) >> errors.err\r"
expect "make"
expect "directory"
expect "errorfile"
expect "continue"
#sleep 1
send --  "\r"
send --  ":cf\r"
expect "warning"
expect "pointer type"
expect "continue"
send --  ":redir END\r"
#expect "continue"
send -- ":q!\r"
expect
exit -onexit {
interact
}
