#!/usr/bin/expect -f
spawn $env(SUBJECTS_SRC_DIR)/vim-5.8 -u $env(HOME)/.vimrc $env(TESTS_SRC)/searchfile
expect "copy1"
sleep 1
send ":se lines=24\r"
send ":se columns=80\r"
send ":redir >> ex_52.4.1.out\r"
send "/\\U\r"
send "\007"
send ":redir END\r"
send ":wq\r"
expect
exit -onexit {
interact
}
