#!/usr/bin/perl

$EXPROOT = "$ENV{experiment_root}/vim";

#Directories
$SRC_DIR = "$EXPROOT/source";
$BIN_DIR = "$EXPROOT/source/bin";

#Files
$COMPILE_OUTPUT_FILE = "$EXPROOT/scripts/compile.logs/COMPILE.$ARGV[0]";

#Commands
$INSTALL_CMD = "make distclean ; make config > $COMPILE_OUTPUT_FILE 2>&1 && make install >> $COMPILE_OUTPUT_FILE 2>&1";

#MAKE VERSION
	print("Installing:   ".$SRC_DIR."\n");
	print("        To:   ".$BIN_DIR."\n");
	print("      With:   ".$ARGV[0]."\n");
	open(FAULTS, ">$SRC_DIR/FaultSeeds.h");
	if(@ARGV == 1)
	{	print FAULTS ("#define $ARGV[0]");	}
	`cd $SRC_DIR && $INSTALL_CMD`;