#!/usr/bin/perl

$EXPROOT = "$ENV{experiment_root}/vim";

#Directories
$BIN_DIR = "$EXPROOT/source/bin";
$IN_DIR = "$EXPROOT/inputs";
$IN_DB = "$EXPROOT/inputs.alt";
$TEST_DIR = "$EXPROOT/testplans.alt";
$OUT_DIR = "$EXPROOT/outputs";
$DIFF_DIR = "$EXPROOT/outputs.alt";
@IGNORED_DIRECTORIES = 
(
    "$TEST_DIR/testplans.fine"
#   "$TEST_DIR/1",
#   "$TEST_DIR/2",
#   "$TEST_DIR/3",
#   "$TEST_DIR/4",
#   "$TEST_DIR/5",
#   "$TEST_DIR/6",
#   "$TEST_DIR/7"
);

#Files
$SCRIPT_FILE = "testfile";
$SETUP_SCRIPT_PREFIX = "setup";
$CLEANUP_SCRIPT_PREFIX = "cleanup";
$FILE_PERMS = "700";

#Commands
$DIRECTORY_LIST_CMD = "ls -1";
$SCRIPT_LIST_CMD = "ls -1 *.expect";

$ENV{SUBJECTS_SRC_DIR} = $BIN_DIR;
$ENV{TESTS_SRC} = $IN_DIR;
$ENV{SHLVL} = 4;

close(STDERR);

$runallflag = !(@ARGV-1) || !(@ARGV);
$i = $ARGV[0];
$test = $ARGV[1];
      
$scriptCounter = 0;
@testDirList = `cd $TEST_DIR && $DIRECTORY_LIST_CMD -F`;
`mkdir $OUT_DIR`;
foreach $level1(@testDirList)
{
	chop($level1);
	$isDirectory = (chop($level1) =~ '/');
	$ignored = grep (/^($TEST_DIR\/$level1)$/, @IGNORED_DIRECTORIES);
	
	if($isDirectory == 1 && $ignored == 0)
	{
		@list = `cd $TEST_DIR/$level1 && $DIRECTORY_LIST_CMD -F`;
		@list = sort{$a cmp $b} @list;
		@list = sort{length($a) cmp length($b)} @list;
		foreach $level2(@list)
		{
			chop($level2);
		
			$isDirectory = (chop($level2) =~ '/');
			$ignored = grep (/^($TEST_DIR\/$level1\/$level2)$/, @IGNORED_DIRECTORIES);
			if($isDirectory == 1 && $ignored == 0)
			{
				@list2 = `cd $TEST_DIR/$level1/$level2 && $SCRIPT_LIST_CMD`;
				@list2 = sort{$a cmp $b} @list2;
				@list2 = sort{length($a) cmp length($b)} @list2;
				foreach $scriptName(@list2)
				{
					if($runallflag || $test == $scriptCounter)
					{
						chop($scriptName);
				
						print(">>>>>>>>running test ".($scriptCounter+1)."\n");
				
						`cp $IN_DB/* $IN_DIR ; chmod $FILE_PERMS $IN_DIR/*`;
				
						@fileParts = split(/\./, $scriptName);
						`cd $TEST_DIR/$level1/$level2 && cat $SETUP_SCRIPT_PREFIX$fileParts[1] $scriptName $CLEANUP_SCRIPT_PREFIX$fileParts[2] > $IN_DIR/$SCRIPT_FILE && chmod $FILE_PERMS $IN_DIR/$SCRIPT_FILE`;
				
						`$IN_DIR/$SCRIPT_FILE`;
				
						$outfile = "$OUT_DIR/t$scriptCounter";
						$difffile = "$DIFF_DIR/v$i/t$scriptCounter";
						
						$num = `ls *.out | wc -l`;
						if($num == 0)
						{
							`mv $IN_DIR/copy1 $outfile`;
						}
						else
						{
							`mv $fileParts[0].$fileParts[1].$fileParts[2].out $outfile`;
						}
						print(`diff -r $outfile $difffile > /dev/null || echo different results`);

						`rm -f -v $IN_DIR/*`;
						`rm -f -v $IN_DIR/.*`;
						`rm -f -v $EXPROOT/scripts/errors.err`;
					}
					$scriptCounter = $scriptCounter + 1;
				}
			}
		}
	}
}

exit();
