#!/usr/bin/perl -w

#$EXPROOT = "$ENV{experiment_root}/bash";

#Directories
#$BIN_DIR = "$EXPROOT/source";
$BIN_DIR = "/home/qxin6/debaug_expt/debaug/benchmark/bash-2.05_template";
$TEST_DIR = "/home/qxin6/debaug_expt/debaug/working/bash/testplans.alt/testplans.fine";
$OUT_DIR = "/home/qxin6/debaug_expt/debaug/working/bash/myoutputs.2";
#$TEST_DIR = "$EXPROOT/testplans.alt/testplans.fine";
#$OUT_DIR = "$EXPROOT/myoutputs.2";
@TORUN_SCRIPTS = `cat $ARGV[0]`;  #Pass in a file that lists the .test files to run

$SCRIPT_FILE = "testfile";

#Commands
$SCRIPT_LIST_CMD = "ls -1 *.test";

$ENV{BASH_SRC_DIR} = $BIN_DIR;
$ENV{TESTS_SRC} = $TEST_DIR;
$ENV{SHLVL} = 4;

close(STDERR);

#$runallflag = !(@ARGV);
#$test = $ARGV[0];

$scriptCounter = 0;
@scriptList = `cd $TEST_DIR && $SCRIPT_LIST_CMD -F`;
@scriptList = sort{$a cmp $b} @scriptList;
`mkdir $OUT_DIR`;
foreach $scriptName(@scriptList)
{
#        print("=== scriptname: ".($scriptName)."\n");
#	chop($scriptName);  # the orig script had 2 chops for some reason -wdm
	chop($scriptName);
	$torun = grep (/^($scriptName)$/, @TORUN_SCRIPTS);
	if($torun != 0)
	{
	    print(">>>>>>>>running test ".($scriptName)."\n");
	    
	    @fileParts = split(/\./, $scriptName);
	    `cd $TEST_DIR && cat setup$fileParts[1] $scriptName cleanup$fileParts[2] > $TEST_DIR/$SCRIPT_FILE && chmod 700 $TEST_DIR/$SCRIPT_FILE`;
	    
	    $outfile = "$OUT_DIR/$scriptName";
	    

	    #`cd $TEST_DIR && $BIN_DIR/bash $TEST_DIR/$SCRIPT_FILE > $outfile`;
	    `cd $TEST_DIR && $BIN_DIR/bash-2.05 $TEST_DIR/$SCRIPT_FILE > $outfile`;
	    $scriptCounter = $scriptCounter + 1;
	}
}
