#!/usr/bin/perl -w

$EXPROOT = "$ENV{experiment_root}/bash";

#Directories
$BIN_DIR = "$EXPROOT/source";
$TEST_DIR = "$EXPROOT/testplans.alt/testplans.fine";
$OUT_DIR = "$EXPROOT/outputs";
@IGNORED_SCRIPTS = 
(

);

$SCRIPT_FILE = "testfile";

#Commands
$SCRIPT_LIST_CMD = "ls -1 *.test";

$ENV{BASH_SRC_DIR} = $BIN_DIR;
$ENV{TESTS_SRC} = $TEST_DIR;
$ENV{SHLVL} = 4;

close(STDERR);

$runallflag = !(@ARGV);
$test = $ARGV[0];

$scriptCounter = 0;
@scriptList = `cd $TEST_DIR && $SCRIPT_LIST_CMD -F`;
@scriptList = sort{$a cmp $b} @scriptList;
`mkdir $OUT_DIR`;
foreach $scriptName(@scriptList)
{
#	chop($scriptName);  # the orig script had 2 chops for some reason -wdm
	chop($scriptName);
	$ignored = grep (/^($scriptName)$/, @IGNORED_SCRIPTS);
	if($ignored == 0)
	{
		if($runallflag || $test == $scriptCounter)
		{
			print(">>>>>>>>running test ".($scriptCounter+1)."\n");

			@fileParts = split(/\./, $scriptName);
			`cd $TEST_DIR && cat setup$fileParts[1] $scriptName cleanup$fileParts[2] > $TEST_DIR/$SCRIPT_FILE && chmod 700 $TEST_DIR/$SCRIPT_FILE`;

			$outfile = "$OUT_DIR/t$scriptCounter";

			
			`cd $TEST_DIR && $BIN_DIR/bash $TEST_DIR/$SCRIPT_FILE > $outfile`;
		}
		$scriptCounter = $scriptCounter + 1;
	}
}
